services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-customer_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-15032002}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

#  eureka-server:
#    image: vladyslavholik/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - zipkin
#
#  api-gateway:
#    image: vladyslavholik/apigateway:latest
#    container_name: api-gateway
#    ports:
#      - "8088:8088"
#    networks:
#      - spring
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - zipkin
#      - eureka-server

  customer:
    image: vladyslavholik/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - fraud
      - rabbitmq
      - postgres
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  fraud:
    image: vladyslavholik/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - postgres
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification:
    image: vladyslavholik/notification:latest
    container_name: notification
    ports:
      - "8086:8086"
    depends_on:
      - zipkin
      - rabbitmq
      - postgres
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
